version: 2.1
orbs:
  newman: postman/newman@1.0.0
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run: 'ls'
      - run: 
          name: 'Replace Secrets'
          command: |
            sed -i -e "s/#{client_id}#/$client_id/g" Spotify.postman_environment.json
            sed -i -e "s/#{client_secret}#/$client_secret/g" Spotify.postman_environment.json
      # - run: './ReplaceSecrets.sh'
      - newman/newman-run:
          collection: ./Spotify.postman_collection.json
          environment: ./Spotify.postman_environment.json