version: 2.1
orbs:
  newman: postman/newman@1.0.0
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run: ./ReplaceSecrets.sh
      - newman/newman-run:
          collection: ./Spotify.postman_collection.json
          environment: ./Spotify.postman_environment.json